import { Suspense } from 'react';
import type { Metadata } from 'next';
import { PublicLayout } from '@/components/layout/PublicLayout';
import { Header } from '@/components/landing/Header';
import { Hero } from '@/components/landing/Hero';
import { ValueProps } from '@/components/landing/ValueProps';
import { QualificationWizard } from '@/components/landing/QualificationWizard';
import { Footer } from '@/components/landing/Footer';
import { TrustedSources } from '@/components/shared/TrustedSources';

const BASE_URL = 'https://ratereliefca.com';

export const metadata: Metadata = {
  alternates: {
    canonical: BASE_URL,
  },
};

// =============================================================================
// CRR-SPECIFIC JSON-LD (was previously in root layout, now scoped to this page
// only so it doesn't bleed onto GRH/SHG/AHB).
// =============================================================================
const organizationSchema = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'California Rate Relief Program',
  url: BASE_URL,
  logo: `${BASE_URL}/img/logo.svg`,
  description:
    'Helping California homeowners reduce their energy bills through the Rate Relief Program. Licensed, bonded, and insured.',
  contactPoint: {
    '@type': 'ContactPoint',
    email: 'info@ratereliefca.com',
    contactType: 'customer service',
    areaServed: 'US-CA',
    availableLanguage: 'English',
  },
  areaServed: {
    '@type': 'State',
    name: 'California',
  },
};

const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': 'LocalBusiness',
  name: 'California Rate Relief Program',
  url: BASE_URL,
  logo: `${BASE_URL}/img/logo.svg`,
  description:
    'Qualify for the 2026 Rate Relief Program. California homeowners can swap their high utility rate for a lower, fixed solar rate.',
  email: 'info@ratereliefca.com',
  areaServed: [{ '@type': 'State', name: 'California' }],
  priceRange: '$0 down',
  serviceType: 'Solar Power Purchase Agreement (PPA)',
};

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'How does the California Rate Relief Program work?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'We install solar panels on your roof at no cost out of pocket. Instead of paying your utility company a different amount every month, you pay a fixed monthly payment that is typically 30 to 50% less than what you are currently paying. The program covers 100% of the cost for solar panels, backup batteries, and installation.',
      },
    },
    {
      '@type': 'Question',
      name: 'Who qualifies for the Rate Relief Program?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'California homeowners with SCE, PG&E, or SDG&E as their utility provider, monthly electric bills of $150 or more, and a credit score of 650 or above typically qualify. Renters are not eligible for this program.',
      },
    },
    {
      '@type': 'Question',
      name: 'Is there any cost to the homeowner?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'There is $0 out of pocket cost. The program covers the full cost of solar panels, battery storage, and professional installation. Instead of paying your utility company, you simply pay a lower, fixed rate for the power generated by the system on your roof.',
      },
    },
    {
      '@type': 'Question',
      name: 'What happens if something breaks?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'The program includes a comprehensive 25-year bumper-to-bumper warranty. If a panel breaks, it gets fixed. If an inverter fails, it gets replaced. All maintenance and repairs are covered at no cost to you for 25 years.',
      },
    },
    {
      '@type': 'Question',
      name: 'Which utility companies are supported?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'The program currently supports homeowners with Southern California Edison (SCE), Pacific Gas & Electric (PG&E), San Diego Gas & Electric (SDG&E), Moreno Valley Utility (MVU), and Los Angeles Department of Water and Power (LADWP).',
      },
    },
  ],
};

// Wrap QualificationWizard in Suspense for useSearchParams
function WizardWithSuspense() {
  return (
    <Suspense
      fallback={
        <section className='py-16 bg-muted/50'>
          <div className='container mx-auto px-4'>
            <div className='max-w-xl mx-auto bg-card rounded-2xl shadow-xl border border-border p-8'>
              <div className='animate-pulse space-y-4'>
                <div className='h-4 bg-muted rounded w-1/3'></div>
                <div className='h-8 bg-muted rounded'></div>
                <div className='grid grid-cols-2 gap-3'>
                  {[1, 2, 3, 4].map((i) => (
                    <div
                      key={i}
                      className='h-20 bg-muted/50 rounded-xl'
                    ></div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>
      }
    >
      <QualificationWizard />
    </Suspense>
  );
}

export default function HomePage() {
  return (
    <PublicLayout>
      <script
        type='application/ld+json'
        dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
      />
      <script
        type='application/ld+json'
        dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }}
      />
      <script
        type='application/ld+json'
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <Header />
      <main>
        <Hero />
        <WizardWithSuspense />
        <ValueProps />
      </main>
      <Footer />
    <div className="container mx-auto px-4 max-w-3xl"><TrustedSources domain="crr" variant="compact" palette={{ fg: 'hsl(var(--foreground))', muted: 'hsl(var(--foreground) / 0.85)', mutedFg: 'hsl(var(--muted-foreground))', accent: 'hsl(var(--primary))', cardBg: 'hsl(var(--card))', cardBorder: 'hsl(var(--border))' }} /></div>
    </PublicLayout>
  );
}
