import { getAllCitySlugs } from '../data/cities-data.ts';

export const GROWTH_ROUTES = [
  ...getAllCitySlugs().map((city) => `/solar-savings/${city}`),
  ...[
    'orange-county',
    'bay-area',
    'inland-empire',
    'central-valley',
    'los-angeles-county',
    'san-diego-county',
  ].map((region) => `/solar-savings/${region}`),
  "/tools/solar-panel-calculator",
  "/best-solar-companies-california",
  "/solar-panels-california",
  "/new-jersey/solar-cost",
  "/new-jersey/solar-companies",
  "/maryland/solar-cost",
  "/maryland/solar-companies",
  "/virginia/solar-cost",
  "/virginia/solar-companies",
  "/virginia/richmond-solar-companies",
  "/virginia/virginia-beach-solar-companies",
  "/blog/best-time-to-install-solar-panels-california",
  "/blog/what-happens-if-stop-paying-solar-lease-california",
  "/maryland/baltimore-solar-companies",
  "/blog/is-community-solar-worth-it",
  "/delaware/solar-cost",
  "/delaware/solar-companies",
  "/washington-dc/solar",
  "/washington-dc/solar-companies",
  "/new-jersey/solar-incentives",
  "/new-jersey/commercial-solar",
  "/maryland/solar-incentives",
  "/virginia/solar-incentives",
  "/delaware/solar-incentives",
  "/washington-dc/solar-incentives",
  "/maryland/bge-high-bill",
  "/maryland/bge-electricity-rates",
  "/utilities/pepco/high-bill",
  "/utilities/pepco/solar-credits",
  "/utilities/delmarva/high-bill",
  "/blog/are-solar-panels-worth-it-california",
  "/blog/sdge-time-of-use-rates-2026",
  "/blog/sce-time-of-use-rates-2026",
  "/commercial-solar/companies-california",
  "/commercial-solar",
  "/blog/solar-tax-credit-expired-2026-options",
  "/blog/california-solar-tax-credit-2026",
  "/blog/solar-tax-credit-2026",
  "/blog/free-solar-for-seniors-california",
  "/blog/free-solar-panels-california",
  "/blog/low-income-solar-california",
  "/blog/ppa-loan-vs-solar-lease-vs-cash-california",
  "/blog/what-is-nem-3-california",
  "/blog/solar-battery-backup-california",
  "/battery/sgip-battery-rebate-california",
  "/battery/home-battery-cost-california",
  "/blog/pge-vs-sce-vs-sdge-rates-compared",
  "/blog/why-is-my-pge-bill-so-high",
  "/blog/why-is-my-california-electric-bill-so-high",
  "/blog/how-to-lower-electric-bill-california",
  "/blog/is-my-roof-good-for-solar-california",
  "/solar-problems/solar-homeowners-insurance",
  "/blog/do-solar-panels-work-during-power-outage-california",
  "/blog/solar-carport-california-guide",
  "/commercial-solar/cost-per-watt-california",
  "/blog/why-is-my-ladwp-bill-so-high",
  "/solar-savings/los-angeles",
  ...[
    "san-diego",
    "fresno",
    "los-angeles",
    "sacramento",
    "bakersfield",
    "san-jose",
    "pleasanton",
    "santa-cruz",
    "el-cajon",
    "modesto",
    "santa-rosa",
    "palm-springs",
    "livermore",
    "palm-desert",
    "chico",
    "murrieta",
    "rocklin",
    "camarillo",
    "san-francisco",
    "oakland",
  ].map((city) => `/solar-companies/${city}`),
  ...[
    "palmetto-solar-review",
    "sunrun-review",
    "solar-optimum-review",
    "sunrun-vs-tesla-solar",
    "trinity-solar-review",
    "sunrun-vs-sunpower",
    "la-solar-group-review",
    "sunergy-solar-review",
    "new-day-solar-review",
    "sullivan-solar-power-review",
    "enphase-vs-solaredge",
    "tesla-solar-review",
    "momentum-solar-review",
    "elevation-solar-review",
    "baker-electric-solar-review",
    "powur-solar-review",
    "sunlux-solar-review",
    "sunnova-review",
    "option-one-solar-review",
    "sunnova-vs-sunrun",
    "empire-solar-review",
    "sunpower-review",
    "ameco-solar-review",
  ].map((slug) => `/solar-installers/${slug}`),
];
// Public local-release candidates deliberately bypass dashboard-session middleware.
// This keeps content review independent of Supabase auth without changing sitemap
// timestamps or ArticleCTA destination behavior, which still use GROWTH_ROUTES.
export const LOCAL_RELEASE_REVIEW_ROUTES = [
  '/solar-companies/riverside',
  '/solar-companies/san-luis-obispo',
  '/solar-companies/temecula',
  '/solar-companies/sonoma',
  '/solar-companies/ventura',
  '/solar-companies/grass-valley',
  '/solar-companies/victorville',
  '/solar-companies/petaluma',
  '/solar-companies/rancho-cucamonga',
  '/solar-companies/santa-barbara',
  '/blog/solar-panels-tile-roof-california',
  '/blog/nem-2-vs-nem-3-california',
  '/blog/nem-3-california-timeline',
  '/blog/nem-3-california-still-worth-it',
  '/blog/net-billing-vs-net-metering-california',
  '/blog/pge-rate-increase-2026',
  '/blog/free-roof-replacement-with-solar-panels-california',
  '/blog/prepaid-ppa-california-2026',
  '/blog/what-happens-to-solar-lease-when-i-sell-california',
  '/blog/commercial-solar-financing-california',
  '/blog/solar-panel-removal-reinstall-cost',
  '/blog/commercial-solar-installation-cost-california',
] as const;

export const PUBLIC_CRR_NO_SESSION_ROUTES = [
  '/email/bill-review',
  '/email/quote-review',
  '/blog/is-solar-worth-it-california-2026',
  ...GROWTH_ROUTES,
  ...LOCAL_RELEASE_REVIEW_ROUTES,
] as const;
