import type { Metadata } from 'next';
import Link from 'next/link';
import { PublicLayout } from '@/components/layout/PublicLayout';
import { Header } from '@/components/landing/Header';
import { Footer } from '@/components/landing/Footer';

const path='/commercial-solar/sgip-battery-storage';
const title="SGIP commercial battery storage: California budget status";
const description="Check current SGIP commercial storage categories, distinguish an existing reservation from a new application, and compare without an assumed rebate.";
export const metadata:Metadata={title,description,alternates:{canonical:path},openGraph:{title,description,type:'article',url:'https://ratereliefca.com'+path,modifiedTime:'2026-09-10T00:00:00Z'}};
export default function SgipCommercialStorage(){
 return <PublicLayout><Header/><main className='mx-auto max-w-3xl px-4 py-12'>
  <script type='application/ld+json' dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:title,dateModified:'2026-09-10',mainEntityOfPage:'https://ratereliefca.com'+path,author:{'@type':'Organization',name:'California Rate Relief'},citation:['https://www.cpuc.ca.gov/sgip','https://www.selfgenca.com/home/program_metrics/']})}}/>
  <Link href='/commercial-solar' className='text-emerald-800 underline'>Commercial solar</Link>
  <h1 className='mt-5 text-3xl font-extrabold leading-tight md:text-5xl'>{title}</h1>
  <p className='mt-4 text-lg'>A commercial battery proposal should work from the program’s current category status. A historic rebate rate or a balance in a closed budget is not an offer of funding.</p>
  <p className='mt-3 text-sm text-slate-600'>Updated September 10, 2026 · California Rate Relief is a private solar referral service.</p>
  <aside className='my-6 rounded-xl border border-amber-300 bg-amber-50 p-5 text-sm'><strong>Correction September 10, 2026.</strong> Earlier availability statements, payment timelines and incentive calculations on this page are withdrawn. The earlier example multiplied $0.30/kWh by 200 kWh and reported $60,000; that multiplication is $60. The units did not support the conclusion. This guide does not use that example or an unverified tax-credit calculation.</aside>
  <div className='space-y-7 [&_h2]:mb-3 [&_h2]:text-2xl [&_h2]:font-bold [&_p]:leading-relaxed'>
   <section><h2>Which commercial categories are closed?</h2><p>The <a href='https://www.selfgenca.com/home/program_metrics/' className='text-emerald-800 underline'>official SGIP tracker</a>, displaying September 10, 2026, marks Large-Scale Storage and Non-Residential Storage Equity closed in the CSE, SCE, SCG and PG&amp;E administrator columns. Equity Resiliency is also closed in those columns. Do not plan a new commercial storage purchase around an assumed reservation in those categories.</p><p className='mt-3'>The table can show remaining funds for a closed category. That does not make the category open to a new application. Confirm an existing reservation and its conditions directly with the administrator; an existing project is a different question from a new applicant.</p></section>
   <section><h2>Residential openings do not establish commercial eligibility</h2><p>The tracker lists separate Residential Solar and Storage Equity AB 209 categories. Some are open or waitlisted. Their presence does not establish an incentive pathway for a commercial building. For a residential project, use the <Link href='/battery/sgip-battery-rebate-california' className='text-emerald-800 underline'>residential category guide</Link>. For a mixed-use or multifamily project, ask the administrator to identify the applicable category and customer requirements in writing.</p></section>
   <section><h2>If the project already has a reservation</h2><ul className='list-disc space-y-2 pl-5'><li>Find the reservation number, administrator, approved equipment and approved incentive amount.</li><li>Confirm the milestones, documents and deadlines that apply to that reservation.</li><li>Ask how a design, ownership or equipment change affects it.</li><li>Separate the amount requested, the amount reserved and the amount actually paid.</li></ul><p className='mt-3'>This guide does not promise an approval or payment timeline. Use the project’s actual correspondence and current program documents.</p></section>
   <section><h2>Compare the battery without an assumed rebate</h2><p>Start with installed cash price, usable capacity, continuous output and the equipment needed for backup. Evaluate the proposed operating schedule against interval usage and the actual commercial tariff. Demand-charge reduction, energy shifting and outage protection need separate assumptions.</p><p className='mt-3'>Have the proposal show which demand peaks the battery can cover, its reserve setting, losses, warranty limits and replacement costs. Compare that result with a solar-only proposal where practical. Keep any conditional incentive outside the base case until the funding position is documented.</p></section>
   <section><h2>Keep incentive units and tax assumptions explicit</h2><p>A rate per watt-hour is not a rate per kilowatt-hour. Match the program’s published unit to the approved capacity before calculating an amount. The same care applies to a quoted percentage: identify what price or basis it applies to.</p><p className='mt-3'>Any interaction with tax credits or depreciation needs a project-specific review using current authority. This page does not calculate those benefits or treat them as cash already received.</p></section>
   <section><h2>Sources checked September 10, 2026</h2><ul className='list-disc space-y-2 pl-5'><li><a href='https://www.cpuc.ca.gov/sgip' className='text-emerald-800 underline'>CPUC SGIP overview and program resources</a></li><li><a href='https://www.selfgenca.com/home/program_metrics/' className='text-emerald-800 underline'>Official program metrics and category status</a></li></ul></section>
  </div>
  <section className='my-9 rounded-xl border bg-emerald-50 p-6'><h2 className='text-2xl font-bold'>Discuss a commercial solar project</h2><p className='my-3'>Tell California Rate Relief about the property, utility and project scope. A provider must confirm service availability, design and price.</p><Link href='/commercial-assessment' className='inline-block rounded-lg bg-emerald-800 px-5 py-3 font-semibold text-white'>Request a commercial assessment</Link></section>
 </main><Footer/></PublicLayout>;
}
