#!/usr/bin/env node
/**
 * City-page gate (Block 3, item 3.5 of the 2026-09-24 SEO plan).
 *
 * A /solar-cost/<city> page may be indexed only when it states at least 3
 * named local data points AND shares under 50% of its 8-word phrases with any
 * sibling page. The rule and the measurement live in src/data/city-gate.ts;
 * this script runs it over every page, prints the table, and keeps the
 * committed snapshot (src/data/city-gate-results.ts) honest. The snapshot is
 * what the routing layer reads (isHeldPath), because it is cheap to import
 * where the full gate (DG Stats JSON, every city's copy) is not.
 *
 * USAGE (from Code/Frontend)
 *   node scripts/city-gate.mjs              # print the table; exit 1 if the snapshot is stale
 *   node scripts/city-gate.mjs --write      # regenerate src/data/city-gate-results.ts
 *   node scripts/city-gate.mjs --json f     # also write the full report as JSON
 *   node scripts/city-gate.mjs --strict     # also exit 1 if any page fails the gate
 *
 * It also fails if a 'use client' module imports the DG Stats loader, which
 * would ship the 350 KB data file to the browser.
 *
 * Needs Node 22.18+ (type stripping on by default) or --experimental-strip-types.
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'src');
const SNAPSHOT = join(SRC, 'data', 'city-gate-results.ts');

const args = process.argv.slice(2);
const flag = (name) => args.includes(name);
const value = (name) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
};

const gate = await import(pathToFileURL(join(SRC, 'data', 'city-gate.ts')).href);
const report = gate.cityGateReport('cost');

// ---------------------------------------------------------------------------
// table
// ---------------------------------------------------------------------------
const pad = (s, n) => String(s).padEnd(n);
console.log(`${pad('page', 34)}${pad('pass', 6)}${pad('overlap', 9)}${pad('nearest', 20)}${pad('points', 8)}words`);
for (const r of [...report].sort((a, b) => b.maxSiblingOverlap - a.maxSiblingOverlap)) {
  console.log(
    `${pad(`/solar-cost/${r.slug}`, 34)}${pad(r.pass ? 'yes' : 'NO', 6)}${pad(`${(r.maxSiblingOverlap * 100).toFixed(1)}%`, 9)}${pad(r.nearestSibling ?? '-', 20)}${pad(r.localDataPoints.length, 8)}${r.words}`,
  );
}
const overlaps = report.map((r) => r.maxSiblingOverlap).sort((a, b) => a - b);
const median = overlaps.length ? overlaps[Math.floor((overlaps.length - 1) / 2)] : 0;
const failing = report.filter((r) => !r.pass);
console.log('');
console.log(`${report.length} pages, ${report.length - failing.length} pass, ${failing.length} fail; median sibling overlap ${(median * 100).toFixed(1)}%, max ${((overlaps.at(-1) ?? 0) * 100).toFixed(1)}%`);
for (const r of failing) console.log(`  FAIL /solar-cost/${r.slug}: ${r.reasons.join('; ')}`);

if (value('--json')) {
  writeFileSync(value('--json'), JSON.stringify({ generated: new Date().toISOString(), median, report }, null, 2));
  console.log(`json report: ${value('--json')}`);
}

// ---------------------------------------------------------------------------
// snapshot
// ---------------------------------------------------------------------------
function snapshotSource() {
  const rows = [...report]
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map(
      (r) =>
        `  ${JSON.stringify(r.slug)}: { pass: ${r.pass}, overlap: ${r.maxSiblingOverlap}, nearest: ${JSON.stringify(r.nearestSibling)}, localDataPoints: ${r.localDataPoints.length} },`,
    );
  return `// GENERATED by scripts/city-gate.mjs --write from src/data/city-gate.ts. Do not edit by hand.
// The committed result of the city-page gate for every /solar-cost/<city> page:
// pass = at least ${gate.MIN_LOCAL_DATA_POINTS} named local data points AND 8-gram overlap with every
// sibling under ${gate.MAX_SIBLING_OVERLAP * 100}%. \`node scripts/city-gate.mjs\` fails when this file no longer
// matches what the gate computes, so a copy or data change cannot leave it stale.
// Small on purpose: middleware and the sitemap can import it without the gate.

export interface CityGateSnapshotRow {
  pass: boolean;
  /** Largest 8-gram overlap with a sibling page, 0-1. */
  overlap: number;
  nearest: string | null;
  localDataPoints: number;
}

export const COST_CITY_GATE: Readonly<Record<string, CityGateSnapshotRow>> = {
${rows.join('\n')}
};

/** Paths of /solar-cost pages that fail the gate and must stay out of the index. */
export const CITY_GATE_FAILING_PATHS: readonly string[] = Object.entries(COST_CITY_GATE)
  .filter(([, row]) => !row.pass)
  .map(([slug]) => \`/solar-cost/\${slug}\`);

/** True for a /solar-cost/<city> path whose page fails the gate. */
export function failsCityGate(path: string): boolean {
  const m = /^\\/solar-cost\\/([a-z0-9-]+)\\/?$/.exec(path);
  return Boolean(m && COST_CITY_GATE[m[1]] && !COST_CITY_GATE[m[1]].pass);
}
`;
}

let exitCode = 0;
const fresh = snapshotSource();
if (flag('--write')) {
  writeFileSync(SNAPSHOT, fresh);
  console.log(`wrote ${relative(ROOT, SNAPSHOT)}`);
} else {
  let current = '';
  try {
    current = readFileSync(SNAPSHOT, 'utf8');
  } catch {
    current = '';
  }
  if (current !== fresh) {
    console.error(`FAIL  ${relative(ROOT, SNAPSHOT)} is stale: run node scripts/city-gate.mjs --write and commit it`);
    exitCode = 1;
  } else {
    console.log(`ok    ${relative(ROOT, SNAPSHOT)} matches the gate`);
  }
}

// ---------------------------------------------------------------------------
// client-bundle check: nothing marked 'use client' may import the DG loader
// ---------------------------------------------------------------------------
function walk(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) walk(path, out);
    else if (/\.(t|j)sx?$/.test(entry.name)) out.push(path);
  }
  return out;
}
const SERVER_ONLY = /from\s+['"][^'"]*(data\/dgstats|dgstats-2026-05-31\.json|lib\/city-cost-content|data\/city-gate['"])/;
const leaks = walk(SRC).filter((file) => {
  const code = readFileSync(file, 'utf8');
  if (!/^\s*['"]use client['"]/m.test(code.slice(0, 200))) return false;
  return code.split('\n').some((line) => SERVER_ONLY.test(line) && !/^\s*import\s+type\b/.test(line));
});
if (leaks.length) {
  console.error(`FAIL  'use client' modules import the server-only DG Stats data: ${leaks.map((f) => relative(ROOT, f)).join(', ')}`);
  exitCode = 1;
} else {
  console.log("ok    no 'use client' module imports the DG Stats data");
}

if (flag('--strict') && failing.length) exitCode = 1;
process.exitCode = exitCode;
